### PR TITLE
Fix/generate locale

### PR DESCRIPTION
**Pull request by jbertel2**
quick patch to support https://github.com/contentstack/gatsby-source-contentstack/issues/42

### CODE REVIEW

**Comment by jbertel2** [comment]
This PR incorporated changes from the create_resolvers_api branch already and was extended until it solved all issues related to schema generation in our use case: we added several fields that are normally available in entries such as locale, uid, publish_details, updated_at and updated_by.

**Comment by vkalta** [comment]
Hi @jbertel2 , is it possible for you to share the example query or any specific use case for these changes?

**Comment by jbertel2** [comment]
Absolutely, glad to discuss why i believe some default fields need to be generated:

When the schema is derived from actual entries, all of these fields are available in the GraphQl schema because they are part of the entry response. But when generating the schema out of the associated contentType definition only (e.g. there are no entries yet), these fields are currently not present, and they Gatsby build breaks due to missing fields in the graphql schema.

The default entry fields i propose to add when generating the schema (more could be added):
- uid: we use uid in our queries to generate unique file paths
- locale: we use locale to generate different pages per locale
- publish_details.locale: we use locale to generate different pages per locale (why does contentstack have 2 locales?)
- updated_at: we display this date in our page footer
- updated_by: not used atm in our use case, but seemed logical to add

Example Query:
```
graphql`
    query($url: String!, $locale: String!) {
        page: contentstackPage(url: { eq: $url }, locale: { eq: $locale }) {
            uid
            title
            url
            updated_at
            ...bodyFields
            ...
    }
`;
```

**Review by vkalta — APPROVED** [review]

**Comment by vkalta** [comment]
@jbertel2 We have released version 2.2.10 with these changes.

Cheers!

**Pull request merged**
